# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dev Server
    before: curl -fsSL https://bun.sh/install | bash &&  echo 'BUN_INSTALL="/home/gitpod/.bun"' >> ~/.bashrc && echo 'PATH="$BUN_INSTALL/bin:$PATH"' >> ~/.bashrc
    init: cd packages/server && bun install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
